layout_spectrum: 0.6371397
typography_spectrum: 0.9810195
color:
  saturation: 0.3184693
  lightness: 0.7700533
  brandStrength: 0.7359399
  rhythmicContrast: 0.5403421
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Opgedoekt
